2021-04-14 20:16:41,198 INFO    MainThread:58 [wandb_setup.py:_flush():69] setting env: {}
2021-04-14 20:16:41,214 INFO    MainThread:58 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-14 20:16:41,214 INFO    MainThread:58 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ada5925ed235ff6eb5aa559add19d37a21f5d86b'}
2021-04-14 20:16:41,215 INFO    MainThread:58 [wandb_init.py:_log_setup():336] Logging user logs to /gdrive/My Drive/To_GPU/wandb/run-20210414_201641-1oxr1tzz/logs/debug.log
2021-04-14 20:16:41,215 INFO    MainThread:58 [wandb_init.py:_log_setup():337] Logging internal logs to /gdrive/My Drive/To_GPU/wandb/run-20210414_201641-1oxr1tzz/logs/debug-internal.log
2021-04-14 20:16:41,216 INFO    MainThread:58 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f257fd63a10>
2021-04-14 20:16:41,216 INFO    MainThread:58 [wandb_init.py:init():369] calling init triggers
2021-04-14 20:16:41,216 INFO    MainThread:58 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-14 20:16:41,216 INFO    MainThread:58 [wandb_init.py:init():418] starting backend
2021-04-14 20:16:41,217 INFO    MainThread:58 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-14 20:16:41,231 INFO    MainThread:58 [backend.py:ensure_launched():123] starting backend process...
2021-04-14 20:16:41,241 INFO    MainThread:58 [backend.py:ensure_launched():128] started backend process with pid: 525
2021-04-14 20:16:41,248 INFO    MainThread:58 [wandb_init.py:init():423] backend started and connected
2021-04-14 20:16:41,315 INFO    MainThread:58 [wandb_init.py:init():465] updated telemetry
2021-04-14 20:16:41,322 INFO    MainThread:58 [wandb_init.py:init():484] communicating current version
2021-04-14 20:16:41,975 INFO    MainThread:58 [wandb_init.py:init():489] got version response 
2021-04-14 20:16:41,975 INFO    MainThread:58 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-14 20:16:46,166 INFO    MainThread:58 [wandb_init.py:init():522] starting run threads in backend
2021-04-14 20:16:48,370 INFO    MainThread:58 [wandb_run.py:_console_start():1524] atexit reg
2021-04-14 20:16:48,379 INFO    MainThread:58 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-04-14 20:16:48,379 INFO    MainThread:58 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-04-14 20:16:48,380 INFO    MainThread:58 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-14 20:16:48,380 INFO    MainThread:58 [wandb_init.py:init():546] run started, returning control to user process
2021-04-14 20:16:48,391 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-04-14 20:16:48,391 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-04-14 20:18:47,979 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-04-14 20:29:59,745 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-04-14 20:29:59,750 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-04-14 20:31:19,174 INFO    MainThread:58 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-04-14 20:31:19,175 INFO    MainThread:58 [wandb_run.py:_restore():1466] restore
2021-04-14 20:31:19,267 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 765
  total_bytes: 765
}

2021-04-14 20:31:19,426 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 765
  total_bytes: 8033
}

2021-04-14 20:31:19,532 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 765
  total_bytes: 8033
}

2021-04-14 20:31:19,633 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8033
  total_bytes: 8033
}

2021-04-14 20:31:19,736 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8033
  total_bytes: 8033
}

2021-04-14 20:31:19,838 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8033
  total_bytes: 8033
}

2021-04-14 20:31:19,940 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8033
  total_bytes: 8033
}

2021-04-14 20:31:20,042 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8033
  total_bytes: 8033
}

2021-04-14 20:31:21,362 INFO    MainThread:58 [wandb_run.py:_show_files():1838] logging synced files
